// <auto-generated />
using System;
using DistroLabb2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DistroLabb2.Migrations.MailDb
{
    [DbContext(typeof(MailDbContext))]
    partial class MailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DistroLabb2.Data.MessageDB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fromUserid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("messageWasRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("theTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("toUserid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("fromUserid");

                    b.HasIndex("toUserid");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("DistroLabb2.Data.UserDB", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("amountDeletedMessage")
                        .HasColumnType("int");

                    b.Property<int>("amountMonthlyLogin")
                        .HasColumnType("int");

                    b.Property<DateTime>("latestLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("nameOfUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DistroLabb2.Data.MessageDB", b =>
                {
                    b.HasOne("DistroLabb2.Data.UserDB", "fromUser")
                        .WithMany()
                        .HasForeignKey("fromUserid");

                    b.HasOne("DistroLabb2.Data.UserDB", "toUser")
                        .WithMany()
                        .HasForeignKey("toUserid");
                });
#pragma warning restore 612, 618
        }
    }
}
